builds:
- env:
  - CGO_ENABLED=0
  binary: devcontainerx
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm64
  main: ./cmd/devcontainerx/
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X "main.goversion={{.Env.GOVERSION}}"

archives:
  - id: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - tap:
      owner: stuartleeks
      name: homebrew-tap
    folder: Formula
    name: devcontainer
    homepage: https://github.com/stuartleeks/devcontainer-cli
    description: CLI for working with Visual Studio Code devcontainers
    install: |
      bin.install "devcontainerx"
    test: |
      system "#{bin}/devcontainerx --version"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
