name: build-and-release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - 'docs/**'

jobs:  
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker BuildKit
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create dummy mount folders
      run: |
        mkdir -p ~/.config/gh
        mkdir -p ~/.azure

    - name: Build and run CLI
      uses: devcontainers/ci@v0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_CROSS_REPO_TOKEN }}
        BUILD_NUMBER: ${{ github.run_id }}
        IS_PR: ${{ github.head_ref }}
        BRANCH: ${{ github.ref }}
      with:
        imageName: ghcr.io/stuartleeks/devcontainer-cli-devcontainer
        runCmd: |
          sudo chown -R $(whoami) /go/pkg
          ./scripts/ci_release.sh
        env: |
          GITHUB_TOKEN
          BUILD_NUMBER
          IS_CI=1
          IS_PR
          BRANCH
